server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Yosemir/config-server
          search-paths: config-microservice
  application:
    name: config-server