server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
       routers:
        - id: account
         uri: lb://account
         predicates: path=/api/v1/account/**
        - id: credit
         uri: lb://credit
         predicates: path=api/v1/customerCredit/**
        - id: customer
         uri: lb://customer
         predicates: path=/api/v1/customer/**
        - id: transaction
         uri: lb://transaction
         predicates: path=/api/v1/transaction/**